<h1>Usuários</h1>

<table class="table">
    <tr>
        <td>ID</td>
        <td>Nome</td>                
        <td>E-mail</td>        
        <td>Ações</td>            
    </tr>
    <?php foreach ($this->data as $registro): ?>
        <tr>
            <td><?php echo $registro->getId();?></td>
            <td><?php echo $registro->getNome();?></td>
            <td><?php echo $registro->getEmail();?></td>            
            <td>
                <?php
                    $linkEdicao = $this->url(
                        'livraria-admin-interna', 
                        array(
                            'controller' => 'usuarios', 
                            'action' => 'edit', 
                            'id' => $registro->getId()
                        )
                    );
                    
                    $linkExclusao = $this->url(
                        'livraria-admin-interna',
                        array(
                            'controller' => 'usuarios',
                            'action' => 'delete',
                            'id' => $registro->getId()
                        )
                    );
                ?>
                <a href="<?php echo $linkEdicao;?>"> Editar </a> &nbsp;
                <a href="<?php echo $linkExclusao;?>"> Excluir </a> &nbsp;                
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<br />
<?php 
    echo $this->paginationControl(
        $this->data,
        'Sliding',
        'paginator'
    );
?>
<hr />
<a href="<?php echo $this->url('livraria-admin', array('controller' => 'usuarios', 'action' => 'new'));?>">Novo registro</a>
