<h1>Novo usuário</h1>
<?php
/*
    $this->form->setAttribute(
        'action', 
        $this->url('livraria-admin', array('controller' => 'categorias', 'action' => 'new'))
    );
 */
    $this->form->prepare();
?>
<?php echo $this->form()->openTag($this->form);?><br />
<?php echo $this->formHidden($this->form->get('id'));?><br />
<?php echo $this->formRow($this->form->get('nome'));?><br />
<?php echo $this->formRow($this->form->get('email'));?><br />
<?php echo $this->formRow($this->form->get('password'));?><br />
<?php echo $this->formSubmit($this->form->get('submit'));?><br />    
<!--<input type="text" name="nome" />-->
<?php
    echo $this->form()->closeTag();
?>