<h1>Categorias</h1>

<table class="table">
    <tr>
        <td>ID</td>
        <td>Nome</td>        
        <td>Ação</td>    
    </tr>
    <?php foreach ($data as $categoria): ?>
        <tr>
            <td><?php echo $categoria->getId();?></td>
            <td><?php echo $categoria->getNome();?></td>
            <td>
                <?php
                    $linkEdicao = $this->url(
                        'livraria-admin-interna', 
                        array(
                            'controller' => 'categorias', 
                            'action' => 'edit', 
                            'id' => $categoria->getId()
                        )
                    );
                    
                    $linkExclusao = $this->url(
                        'livraria-admin-interna',
                        array(
                            'controller' => 'categorias',
                            'action' => 'delete',
                            'id' => $categoria->getId()
                        )
                    );
                ?>
                <a href="<?php echo $linkEdicao;?>"> Editar </a> &nbsp;
                <a href="<?php echo $linkExclusao;?>"> Excluir </a> &nbsp;                
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<br />
<?php 
    echo $this->paginationControl(
        $this->data,
        'Sliding',
        'paginator'
    );
?>
<hr />
<a href="<?php echo $this->url('livraria-admin', array('controller' => 'categorias', 'action' => 'new'));?>">Novo registro</a>
