<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function($page) use($urlPattern) {
    if (! preg_match('/page/', $urlPattern)) {
        return $urlPattern . '/page/' . $page;
    } else {
        return preg_replace('/\d+/', $page, $urlPattern);
    }
}
?>


<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $formatUrl($this->previous);?>">
                &lt; Previous
            </a> |
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $formatUrl($page);?>">
                    <?php echo $page; ?>
                </a> |
            <?php else: ?>
                <?php echo $page; ?> |
           <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $formatUrl($this->next); ?>">
                Next &gt;
            </a>
        <?php else: ?>
            <span class="disabled">Next &gt;</span>
        <?php endif; ?>
    </div>
<?php endif; ?>